const fs = require('fs');
const path = require('path');

function walkDir(dir, callback) {
    fs.readdirSync(dir).forEach(f => {
        let dirPath = path.join(dir, f);
        let isDirectory = fs.statSync(dirPath).isDirectory();
        isDirectory ? walkDir(dirPath, callback) : callback(path.join(dir, f));
    });
}

// Fix class -> className in legacy pages
walkDir(path.join(__dirname, '_pages_legacy'), (filePath) => {
    if (!filePath.endsWith('.tsx') && !filePath.endsWith('.ts')) return;
    let content = fs.readFileSync(filePath, 'utf8');
    let original = content;

    content = content.replace(/ class="/g, ' className="');
    content = content.replace(/to="/g, 'href="');

    if (content !== original) {
        fs.writeFileSync(filePath, content, 'utf8');
        console.log('Fixed syntax in:', filePath);
    }
});

// Fix trailing spaces in app folder components generated by our script
walkDir(path.join(__dirname, 'app'), (filePath) => {
    if (!filePath.endsWith('page.tsx')) return;
    let content = fs.readFileSync(filePath, 'utf8');
    if (content.includes(" '")) {
        const fixedContent = content.replace(/([A-Za-z0-9]+) '/g, "$1'");
        fs.writeFileSync(filePath, fixedContent, 'utf8');
        console.log('Fixed import in:', filePath);
    }
});
