import { ForumPost } from '../types/federation';

export const initialForumPosts: ForumPost[] = [
    {
        id: '1',
        author: 'Dr. V. Raghavan',
        specialty: 'Ayurvedic Oncology',
        category: 'Clinical Research',
        title: 'Efficacy of Suvarna Bhasma in Adjuvant Protocols for Solid Tumors',
        content: 'I have observed promising results...',
        upvotes: 142,
        comments: 34,
        status: 'approved',
        timestamp: 'MAR 08, 2026',
    },
    {
        id: '2',
        author: 'Dr. Anita Desai',
        specialty: 'Dermatology & Cosmetology',
        category: 'Case Study',
        title: 'Long-term Management of Psoriasis using Modified Panchakarma',
        content: 'A recent case series shows...',
        upvotes: 89,
        comments: 12,
        status: 'approved',
        timestamp: 'MAR 05, 2026',
    },
    {
        id: '3',
        author: 'Prof. S. N. Murthy',
        specialty: 'Pharmacognosy',
        category: 'Herbology',
        title: 'Standardization Markers for Quality Control of Ashwagandha Extracts',
        content: 'Standardizing these markers is essential for consistent efficacy.',
        upvotes: 215,
        comments: 48,
        status: 'approved',
        timestamp: 'FEB 28, 2026',
    },
    {
        id: '4',
        author: 'Dr. Meera N.',
        specialty: 'Pediatrics',
        category: 'Discussion',
        title: 'Integration of Swarnaprashana in Modern Immunization Schedules',
        content: 'Is there potential to integrate this with standard vaccination schedules?',
        upvotes: 0,
        comments: 0,
        status: 'pending',
        timestamp: 'MAR 09, 2026',
    },
    {
        id: '5',
        author: 'Dr. K. Iyer',
        specialty: 'Internal Medicine',
        category: 'Clinical Trial',
        title: 'Phase II Data: Herbomineral compounds in uncontrolled Type 2 Diabetes',
        content: 'Data from our Phase II trial indicates...',
        upvotes: 0,
        comments: 0,
        status: 'pending',
        timestamp: 'MAR 09, 2026',
    }
];
